name: Cypress Cloud Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v4
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v6
       with:
         command: npm run lambdatestcypress
